export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const GET_PATIENT_DATA = "GET_PATIENT_DATA";
export const GET_STAFF_LIST = "GET_STAFF_LIST";
export const GET_ALL_DEPARTMENTS = "GET_ALL_DEPARTMENTS";
export const GET_ALL_JOBS_FOR_DEPARTMENT = "GET_ALL_JOBS_FOR_DEPARTMENT";
